name: PR to develop branch from feature branch.

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    name: 'Install dependencies, lint, test and build package.'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies 🔧
        run: npm install

      - name: Run graphql codegen (indexer) 🔧
        run: npm run codegen

      - name: Run linter 🔍
        run: npm run lint

      - name: Run tests 🧪
        run: npm run test

      - name: Build package 📦
        run: npm run build
